"shell script
setlocal expandtab 
setlocal tabstop=4 
setlocal shiftwidth=4 
setlocal softtabstop=4
setlocal smarttab
setlocal sh=bash
setlocal foldmethod=indent
setlocal omnifunc=te#bashcomplete#omnicomplete
